Repository IE-bbuda/mozi-frontend, pull requests merged in 2025-08, with the labels that each got.

#50 마이페이지(정보 수정, 퍼스널 정보 등록) 화면 구현
  src/pages/auth/LoginPage.vue
  src/pages/user/CustomDropdown.vue
  src/pages/user/EditInfo.vue
  src/pages/user/MultiStep.vue
  src/pages/user/MyPage.vue
  src/pages/user/PersonalInfo.vue
  src/router/index.js
  src/router/user.js
Labels: enhancement

#53 feat: 스크랩(금융) 조회, 저장, 삭제 기능 구현
  src/api/scrapApi.js
  src/pages/scrap/ScrapPage.vue
  src/pages/search/financialSearch/DepositDetailPage.vue
  src/pages/search/financialSearch/FinancialSearchPage.vue
  src/pages/search/financialSearch/SavingDetailPage.vue
  src/pages/search/financialSearch/financialCard.vue
  src/pages/search/policySearch/policyCard.vue
  src/pages/search/policySearch/policyDetailPage.vue
Labels: 🐞bug, enhancement, ✨ Feature

#70 Feature/back user
  src/api/auth.js
  src/pages/auth/FindIDPage.vue
  vite.config.js
Labels: enhancement

#97 feat: google, naver OAuth 추가를 위한 화면 수정
  src/pages/auth/LoginPage.vue
  src/pages/auth/OAuthCallbackPage.vue
  src/router/index.js
Labels: enhancement

#137 회원가입, 마이페이지 기능구현 및 UI 보완
  src/pages/auth/FindIDPage.vue
  src/pages/auth/FindPasswdPage.vue
  src/pages/auth/JoinPage.vue
  src/pages/auth/LoginPage.vue
  src/pages/auth/ResetPasswdPage.vue
  src/pages/user/EditInfo.vue
  src/pages/user/MyPage.vue
  src/pages/user/PersonalInfo.vue
  vite.config.js
Labels: enhancement

#148 style: 페이지 전반 공통 UI 및 대표 색상 적용
  src/pages/MainPage.vue
  src/pages/account/BankSummaryPage.vue
  src/pages/auth/LoginPage.vue
  src/pages/goal/GoalDetailView.vue
  src/pages/goal/GoalMainView.vue
  src/pages/recommend/RecommendPage.vue
  src/pages/search/SearchGuidePage.vue
  src/pages/search/financialSearch/DepositDetailPage.vue
  src/pages/search/financialSearch/FinancialSearchPage.vue
  src/pages/search/financialSearch/SavingDetailPage.vue
  src/pages/search/financialSearch/financialFilter.vue
  src/pages/search/policySearch/PolicySearchPage.vue
  src/pages/search/policySearch/policyCard.vue
  src/pages/search/policySearch/policyDetailPage.vue
Labels: enhancement

#168 계정 탈퇴 페이지 및 기능 추가
  src/constants/enums.js
  src/pages/user/DeleteInfo.vue
  src/pages/user/MyPage.vue
  src/router/user.js
Labels: enhancement

#182 fix: 기간 필터링 적용 오류 수정
  src/pages/search/financialSearch/FinancialFilter.vue
  src/pages/search/financialSearch/FinancialSearchPage.vue
  src/pages/search/financialSearch/SavingDetailPage.vue
Labels: 🐞bug, enhancement

#186 feat: favicon 이미지 추가
  index.html
  public/favicon.ico
  public/images/account/accountEmpty.png
  public/images/account/unlinkAccountEmpty.png
  public/images/recommend/noGoal.png
  src/pages/account/BankSummaryPage.vue
  src/pages/account/BankUnlinkPage.vue
  src/pages/recommend/financial/FinancialRecommendTab.vue
  src/pages/recommend/policy/PolicyRecommendTab.vue
Labels: enhancement
